# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['volunteer__first_name', 'volunteer__last_name']},
        ),
        migrations.AlterField(
            model_name='shift',
            name='managers_in_charge',
            field=models.ManyToManyField(blank=True, to='tvsa.Volunteer'),
        ),
    ]
