# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvsa', '0002_auto_20160719_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['last_name']},
        ),
    ]
