# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvsa', '0003_auto_20160728_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='tvsa.Job'),
        ),
    ]
